### Basic POST items

POST http://localhost:3000/api/v1/items HTTP/1.1
content-type: application/json

[{
    "videoTitle": "sample",
    "videoId": "juejue",
    "channelId": "qweqwe"
}]

### POST items with multiple real items

POST http://localhost:3000/api/v1/items HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZW1haWwiOiJxd2Vxd2VAcXdlcXdlLmNvbSIsInByZWZlcnJlZExhbmd1YWdlIjoiIn0.S1awtPD4DnV_JuJpBgS0OXIN8XQef464YLxTcWzIQDY

[
    {"videoTitle":"Los MEJORES Cascos Gaming INALÁMBRICOS del 2022","videoId":"Faon55nT8MI","channelId":"/@new3sc"},
    {"videoTitle":"We Bought a Giant Movie CD Player and its AMAZING","videoId":"z9XWN7u8mSU","channelId":"/@LinusTechTips"},
    {"videoTitle":"My YouTuber merch is not the best.. :(","videoId":"akxU62laPMk","channelId":"/@LinusTechTips"}
]


### Basic GET items

GET http://localhost:3000/api/v1/search?q=us HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZW1haWwiOiJxd2Vxd2VAcXdlcXdlLmNvbSIsInByZWZlcnJlZExhbmd1YWdlIjoiIn0.S1awtPD4DnV_JuJpBgS0OXIN8XQef464YLxTcWzIQDY


### Auth Login

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{"email": "qweqwe@qweqwe.com", "password": "qweqwe"}


### Auth Signup

POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json

{"email": "qweqwe@qweqwe.com", "password": "qweqwe"}