version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=tracetube
      - POSTGRES_USER=tracetube
      - POSTGRES_DB=tracetube
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    ports:
      - 55432:5432

  api:
    image: victor141516/tracetube-ng
    build: .
    environment:
      - DATABASE_URI=postgres://tracetube:tracetube@postgres:5432/tracetube
    ports:
      - 3000:3000
    depends_on:
      - postgres

  worker:
    image: victor141516/tracetube-ng
    build: .
    environment:
      - DATABASE_URI=postgres://tracetube:tracetube@postgres:5432/tracetube
      - MODE=worker
    depends_on:
      - postgres

  
