version: "3.9"

networks:
  caddywork:
    external: true

services:
  postgres:
    networks:
      - default

  api:
    environment:
      - DATABASE_URI=postgres://tracetube:tracetube@postgres:5432/tracetube
      - CHROME_EXTENSION_URL_ORIGIN=jonllnplkagdoikjajkgdbjcojnhjjoe
    networks:
      - default
      - caddywork
    env_file:
      - $HOME/secrets/TraceTube-ng/env

  worker:
    networks:
      - default
